version: "3.9"
services:
  minecraft:
    image: "buddyspencer/papermc:1.20.2"
    restart: always
    container_name: "mcserver"
    environment:
      MEMORYSIZE: "1G"
      PAPERMC_FLAGS: ""
    volumes:
      - "./server:/data:rw"
      - "./build/ItemChestSorter-1.14.4.jar:/data/plugins/ItemChestSorter.jar:ro"
    ports:
      - "25565:25565"
    # The following allow `docker attach mcserver` to work
    stdin_open: true
    tty: true